### ISSUE TITLE
[BUG] creating team requires me invite someone and inviting people is kinda broken

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#15]
**Describe the bug**
1: when creating a team it requires me to enter something

**Include relevant information**
https://drive.google.com/file/d/1x39CkaA9v8BVXGc9OhM-QaIZrL2OLudt/view?usp=sharing

**To Reproduce**
1. go to create team 
2. create a team name
3. press create 
5. see the error asking you to fill the invite member

**Expected behavior**
let me create a team without people, i like being alone

**Screenshots**
https://drive.google.com/file/d/1x39CkaA9v8BVXGc9OhM-QaIZrL2OLudt/view?usp=sharing

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

**Comment by Forest-Gio** [comment]
the fix has been deployed
