### ISSUE TITLE
make search also search on domains

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#16]
**Is your feature request related to a problem? Please describe.**
currently when you search on forest it only tries to search the title. I need to rely on internal documentation to find out if it is even on forest.

**Describe the solution you'd like**
when i type a domain in the search bar it would also search by domain. when it has a hit by domain have a little tag wich says "found by domain" 

**Describe alternatives you've considered**
you could have an internal document with every url and forest url.

**Additional context**
something like this
<img width="608" alt="Screenshot 2023-01-30 at 16 28 20" src="https://user-images.githubusercontent.com/39672378/215519938-a2332435-cdb8-472b-b532-60d1417700ed.png">

**Comment by mass-im** [comment]
Good idea! I think, in the current situation, it might be worth to think about naming conventions.
We are working towards this being possible for the main domains of an environment, so I'm going to close this for now.
