### ISSUE TITLE
[BUG] Updating variable doesn't work anymore after deleting the variable

### ISSUE THREAD

**Issue by robinriggs** [forest-host/support#17]
**Describe the bug**
After clicking on updating an environment variable, I've deleted it to make a new one, but the update field below still stays and is unresponsive

**Comment by mass-im** [comment]
Thanks for letting us know! Could you share with us the environment ID this is about?

@Forest-Gio is this a situation/bug you are aware of?

**Comment by mass-im** [comment]
@robinriggs I'm closing this for now. We need some more information to find out what is going wrong here. I'll walk to your desk when you're back at the office.
