### ISSUE TITLE
[BUG] Spike in a response time

### ISSUE THREAD

**Issue by bohdangoeshike** [forest-host/support#18]
**Describe the bug**
Today around 14:00 pm there was a spike in the response time for some websites hosted on Forrest. 

**Include relevant information**
Websites were loading slowly during that time. It affected not only live websites, but also the one's that are on staging environments. Some clients said reported that the websites were also down. Although this was not detected by the uptimerobot. 

**Expected behavior**
Expect these things not to happen.

**Screenshots**
Looked something like these: 
1
![Screenshot from 2023-02-03 17-10-56](https://user-images.githubusercontent.com/124379166/216645185-21fc8230-8164-4549-affc-f83918104176.png)
2
![Screenshot from 2023-02-03 17-18-43](https://user-images.githubusercontent.com/124379166/216645205-22490dbe-90d3-4e9a-9541-814ac92fdaec.png)
3
![Screenshot from 2023-02-03 17-15-00](https://user-images.githubusercontent.com/124379166/216645239-7184c1f2-6bc3-412f-8581-92a99a44abfe.png)

**Comment by mass-im** [comment]
Hey Bohdan!

Thanks for letting us know. We heard already but I thought for completeness sake this deserves an answer :)
We spend the last ~7 days improving this. With this I mean traffic to one application impacting performance of another one.
If it happens again, please let us know of course!
