### ISSUE TITLE
[BUG] when opening a large log file my browser freezes

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#20]
**Describe the bug**
when i open a large log file such as the info log of CENSORED it tries to open the intire log wich my browser cant handle

**Include relevant information**
it's on CENSORED master 

**To Reproduce**
1. go to CENSORED master on forest
2. open the log file
3. select node and info 
4. your browser now freezes

**Expected behavior**
it not showing the intire log but only like the last 100 lines and notifying me that the log has been truncated 

**Screenshots**
no

**Check for sensitive information**
no lol

**Comment by mass-im** [comment]
Thanks for letting us know!
We will improve this.

**Comment by mass-im** [comment]
Fixes going live today. NodeJS is already updated. To enjoy smaller logs dont forget to redeploy.
