### ISSUE TITLE
[BUG] Can't add numbers in the domains i add to my project

### ISSUE THREAD

**Issue by sjaakbanaan** [forest-host/support#21]
**Describe the bug**
Right now it's not possible to add numbers in the domains overview on a project.

**To Reproduce**
1. Go to a project on Forest'
2. Click on 'Domains'
3. Try to add a domain that contains numbers, you will see an error

**Expected behavior**
That it's allowed.

**Screenshots**
Screenshots are shared privately.

**Comment by Forest-Gio** [comment]
this has been fixed!
