### ISSUE TITLE
[BUG] cannot redeploy really old commits

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#25]
**Describe the bug**
I made a mistake 15 commits ago and i wanted to revert to a state where everything worked but when pressing on redeploy it loads for a while and then says failed due to a internal forest.host error

**Include relevant information**
buildid: 91ad9857-87f7-46e4-bc4c-77d5cb39cabe

**To Reproduce**
1. goto deploys
2. select and old deploy and wait

**Expected behavior**
it not failing

**Screenshots**

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

**Comment by Forest-Gio** [comment]
Hey! Re-deploys happen from the cached builds. I am unsure how long these builds are cached, i'll have to inform that, will get back to you whenever i have an answer to that. But I reckon the build is not in the cache anymore hence why the re-deploy is not working
