### ISSUE TITLE
[BUG] no fallback if you misconfigure indexfile in blueprint builder

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#27]
**Describe the bug**
see title

**Include relevant information**

**To Reproduce**
1. create a new project
2. go create a node service
3. in the node service configure all the build commands
4. configure the build path
5. in index file write something that doesnt exist

**Expected behavior**
it throwing an error saying it cant find the index file

**Screenshots**

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

build id :26a9932c-0646-46b0-8eeb-bec2ac8ad996

**Comment by Forest-Gio** [comment]
Hey!

I do not understand how this is a bug when you are the person telling Forest what to do.

Forest is the machine that executes what you tell it to execute.

I'll discuss with Massim if this is something we can implement better but i'm not sure how this is Forest's fault. 

Closing this issue for now
