### ISSUE TITLE
[BUG] no nginx config on the php 8 environment 

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#28]
**Describe the bug**
in the blueprint builder there is an option to edit the nginx files, on php 8 this option doesnt exist.

**Include relevant information**
When reporting in issue about environments, builds, databases or volumes include the IDs that are relevant. IDs might be part of the URL or can be found in the response for the relevant page or request.
(don't share project and environment names if you can. See `check for sensitive information` at the end of the template)

**To Reproduce**
1. Go to the blueprint buidler
2. create an php8 service 
3. go to the files tab of the php8 service
4. boom no nginx config to edit

**Expected behavior**
it let's me edit the nginx file

**Comment by Forest-Gio** [comment]
Hey!

Thank you for your bug report.

The NGINX config you get from our pre-made blueprints are pre-configured.

When you create your own blueprint the services are not pre-configured and to you to configure to your liking.

You can always go to the files tab for a service and create an nginx config yourself, i've added a video to this comment to show you how to do so.

Closing this issue as this isn't a bug.

Thank you!
![Peek 2023-03-24 12-56](https://user-images.githubusercontent.com/103750548/227515050-f7200c8d-b661-42d7-bf29-bb8143413e2c.gif)
