### ISSUE TITLE
[BUG] 503 errors when having duplicate nginx settings

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#29]
**Describe the bug**
So when you edit a nginx config for a php service and you set 2 duplicate values such as "fastcgi_pass" nginx chrashes in the container thus causing a 503

**Include relevant information**

**To Reproduce**
1. Go to the nginx config of a site 
2. add a second `fastcgi_pass` as seen in the example
3. redeploy 
4. go to the url of the service

**Expected behavior**
forest showing me an error of how i messed up the nginx config

**example**
```
server {
  root /var/www/web;
  index {{= it.INDEX_FILE }};

  # Prevent PHP scripts from being executed inside the uploads folder.
  location ~* /app/uploads/.*.php$ {
    deny all;
  }

  location / {
    try_files $uri $uri/ /{{= it.INDEX_FILE }}?$args;
  }

  location ~ \.php$ {
    fastcgi_cache phpcache;
    fastcgi_cache_valid 200 301 302 60m;
    fastcgi_cache_use_stale error timeout updating invalid_header http_500 http_503;
    fastcgi_cache_min_uses 1;
    fastcgi_cache_lock on;
    add_header X-FastCGI-Cache $upstream_cache_status;

    include snippets/fastcgi-php.conf;
    include fastcgi_params;

    fastcgi_pass 127.0.0.1:9000;
    fastcgi_pass 127.0.0.1:9000; # this line causes errors

  }
}
```

**Check for sensitive information**

**Comment by Forest-Gio** [comment]
Hey,

Again i fail to see how this is an issue with Forest and not an issue with you not watching what you're doing better.

I'll discuss with Massim if we want to implement this kind of functionality, but i am not sure how we'd do that without analyzing User data or making the App too complex.

We'll come back to this, but i'm closing this for now.

Again; my tip would be to double read what you're doing, and not just fill something in and expect it to work.

Thank you for your report!
