### ISSUE TITLE
[BUG] Build seems to hang/stop working

### ISSUE THREAD

**Issue by sjaakbanaan** [Forest-Host/support#3]
**Describe the bug**
Build of App (frontend) seems to hang/stop working.

**Expected behavior**
Previous build took only like 3 or 4 minutes. This time we're over 10 minutes already. 

**Include relevant information**
build id: b5ae1772-9a88-4a0c-8921-7a7a080a3b9c

**Comment by mass-im** [comment]
Thanks for letting us know!

**Comment by mass-im** [comment]
To add to this:
The build status is `building` and the build takes so long it seems to be stuck.
This is now a known issue. When a build is stuck it looks like it is still building, from a users perspective. While it is not doing anything anymore.
Will fix!
