### ISSUE TITLE
[BUG] build page keeps saying build is pending

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#31]
**Describe the bug**
so when you are on your project: `projects/hike/{website}/master/builds/{buildid}` and press redeploy it doesnt do anything 

**To Reproduce**
1. go to your forest home page
2. click on the failed build
3. press on this screen redeploy

**Expected behavior**
it keeps updating the build status

**Screenshots**
i am not allowed to share it

btw it's very strange when you redeploy on this screen it keeps showing the output of the previous build

**Comment by Forest-Gio** [comment]
Hey!

This is expected behaviour.

The build log page doesn't update in real time (yet).

This will be changed in the near future, so for now this is expected behaviour.

Thank you for your bug report!
