### ISSUE TITLE
[BUG] php8 service uses php7.4 in the builder

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#35]
**Describe the bug**
When you use php8 it builds composer with php7.4

**Include relevant information**

**To Reproduce**
1. create new env with the template bedrock + nextjs
2. replace the php7.4 service with php8 
3. add the build command `php -v` to php8
4. deploy 
5. ???
6. check the build logs

**Expected behavior**
it uses php8 to build 

**Screenshots**

**Comment by mass-im** [comment]
Yeah I am aware of this situation. We currently have a single builder image we use.
So maybe we need that to be on PHP8 (and eventually we probably need choosing a version to be a feature)

**Comment by cvanh** [comment]
yes, as per the screenshot
