### ISSUE TITLE
[BUG] nodejs service is being autofilled when editing php service

### ISSUE THREAD

**Issue by cvanh** [forest-host/support#36]
**Describe the bug**
when i try to type commands in the php service they are being autofilled in nodejs regardless of the input of these fields

**Include relevant information**
ur mom lol

**To Reproduce**

https://user-images.githubusercontent.com/39672378/231715708-082bfb7d-5a83-4b67-bb08-44feb6b334f5.mov

**Expected behavior**
it not autofilling the other service. 

**Screenshots**

**Comment by mass-im** [comment]
Thanks for reporting! Very annoying bug. Fix is on the way

**Comment by Forest-Gio** [comment]
This has been fixed!

Thank you for reporting this issue to Forest.

If encounter more bugs, or have any feedback; please feel free to create another issue!

Ciao for now,

Giovanni
