### ISSUE TITLE
[BUG] blueprint builder doesnt save 

### ISSUE THREAD

**Issue by cvanh** [Forest-Host/support#4]
**Describe the bug**
When I want so save something after deleting a service is doesn't save the blueprint

**Include relevant information**
environment id: 007269e5-2853-4dcb-bb9e-246e752633dc 
template: Bedrock (multisite subfolders) on PHP 7.4 + Node 12

**To Reproduce**
1. Go to blueprint builder
2. click on edit 
3. add nodejs 14 service
4. copy the build command index file and deploy path from the old node 12 to the new node 14 service
5. remove the old node 12
6 .click on save 
7. look in network tab and see a request with the status code 400. 

the failing request returns 
{"error":{"repositories":{"2":{"services":{"0":{"name":"Value should be in array: ['NodeJS 14','PHP 7.4','phpMyAdmin']"}}}}}}

**Expected behavior**
the blueprint that saves

**Screenshots**
idk i can make a video

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

**Comment by Forest-Gio** [comment]
thank you for your bug report. 

i'll try fixing this bug ASAP

**Comment by Forest-Gio** [comment]
bug has been fixed and merged into upstream @cvanh
