### ISSUE TITLE
[BUG] blueprints wont save

### ISSUE THREAD

**Issue by cvanh** [Forest-Host/support#5]
**Describe the bug**
when i edit a blueprint and press save and then go back to check if it saved it didnt save

**Include relevant information**
the only hint i see is that the gateway time outs and only sends cache-control and chache-type: text-html headers. no cors headers 

**To Reproduce**
1. go to blueprint
2. add a build command
3. press save
4. wait for it to timeout
5. go back to the blueprint builder
6. see that the command you just added didnt save

**Expected behavior**
it saves

**Screenshots**
<img width="578" alt="Screenshot 2022-11-12 at 16 25 28" src="https://user-images.githubusercontent.com/39672378/201481226-5e92dcb3-0398-4f2c-bbe1-b210cfe4a051.png">

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

**Comment by mass-im** [comment]
Thanks for the report. This is indeed a bug.
The API attempts to deploy the static services in your environment while they already are deployed.

Ref: https://github.com/Forest-Host/api/issues/45
