### ISSUE TITLE
[BUG] cannot delete domain of project

### ISSUE THREAD

**Issue by cvanh** [Forest-Host/support#6]
**Describe the bug**
when i want to want to remove an failed domain it doesnt work. and if it works its slow like really slow

**Include relevant information**
team id: c68f28af-a896-468e-bc04-4acf6514062d
project id: 2208acf6-310f-4df8-b9e3-4ca35b528cae

**To Reproduce**
1. make shure the domain creation has failed(see screenshot) 
2. try to remove it
3. enter the domain in the field
4. press remove domain and then reload the browser
5. repeat this a few times i guess
6. ??
7. try it again and you will see an error from the api such as 500-{}

**Expected behavior**
that the domain is removed in a speedy fashion

**Screenshots**
<img width="832" alt="Screenshot 2022-11-16 at 23 20 04" src="https://user-images.githubusercontent.com/39672378/202306840-b1908878-fe07-4b2b-948b-3e9ae0de5714.png">
<img width="454" alt="Screenshot 2022-11-16 at 23 21 27" src="https://user-images.githubusercontent.com/39672378/202307085-59410368-ce74-4301-b681-e4f07b6f1769.png">

**Check for sensitive information**
If you find yourself wanting to share the name of a project, environment or domain, try to find the ID.
This prevents sharing sensitive information in a public space. You can always contact us on Slack or send a message to massim@forest.host.

**Comment by mass-im** [comment]
Thanks for reporting. This is a known bug that occurs when adding a domain that has no record pointing to Forest. Fix is ready and currently under testing, will go live beginning of next week.
